const fs = require('fs');
const path = require('path');

const publicDir = 'e:/PortfolioVAn/public';
const dataFile = 'e:/PortfolioVAn/app/mc/data.ts';

function slugify(text) {
    return text.toString().toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^\w\-]+/g, '')
        .replace(/\-\-+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
}

function removeAccents(str) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D');
}

const folders = fs.readdirSync(publicDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name)
    .filter(name => !['VAN', 'Ảnh đẹp để giới thiệu'].includes(name));

const projects = [];
const projectDetails = {};

for (const folder of folders) {
    const slug = slugify(removeAccents(folder));
    const title = folder.replace(/_/g, ' ');
    const folderPath = path.join(publicDir, folder);
    const files = fs.readdirSync(folderPath);
    
    const validFiles = files.filter(f => f.match(/\.(jpg|jpeg|png|webp)$/i));
    
    if (validFiles.length > 0) {
        const imageFile = validFiles[0];
        projects.push({
            title: title,
            slug: slug,
            role: "Dẫn chương trình",
            image: `/${encodeURI(folder)}/${encodeURI(imageFile)}`
        });
        
        projectDetails[slug] = {
            title: title,
            images: validFiles.map(f => `/${encodeURI(folder)}/${encodeURI(f)}`)
        };
    }
}

const content = `// Auto-generated by generate_static_data.js
export const projects = ${JSON.stringify(projects, null, 2)};

export const projectDetails: Record<string, { title: string, images: string[] }> = ${JSON.stringify(projectDetails, null, 2)};
`;

fs.writeFileSync(dataFile, content, 'utf8');
console.log('Successfully generated static data!');
