const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const publicDir = path.join(__dirname, 'public');
const optimizedDir = path.join(publicDir, 'optimized');
const dataFile = path.join(__dirname, 'app/mc/data.ts');

function slugify(text) {
    return text.toString().toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^\w\-]+/g, '')
        .replace(/\-\-+/g, '-')
        .replace(/^-+/, '')
        .replace(/-+$/, '');
}

function removeAccents(str) {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D');
}

async function run() {
    if (!fs.existsSync(optimizedDir)) {
        fs.mkdirSync(optimizedDir, { recursive: true });
    }

    const folders = fs.readdirSync(publicDir, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name)
        .filter(name => !['VAN', 'Ảnh đẹp để giới thiệu', 'optimized'].includes(name));

    const projects = [];
    const projectDetails = {};

    console.log('Starting image optimization. This might take a bit for large images...');

    for (const folder of folders) {
        const slug = slugify(removeAccents(folder));
        const title = folder.replace(/_/g, ' ');
        const folderPath = path.join(publicDir, folder);
        
        // Also create a subfolder in optimized
        const optimizedFolderPath = path.join(optimizedDir, folder);
        if (!fs.existsSync(optimizedFolderPath)) {
            fs.mkdirSync(optimizedFolderPath, { recursive: true });
        }

        const files = fs.readdirSync(folderPath);
        const validFiles = files.filter(f => f.match(/\.(jpg|jpeg|png|webp)$/i));
        
        if (validFiles.length > 0) {
            console.log(`Processing folder: ${folder} (${validFiles.length} images)`);
            
            const galleryImages = [];
            let coverImage = '';

            for (let i = 0; i < validFiles.length; i++) {
                const file = validFiles[i];
                const inputPath = path.join(folderPath, file);
                const fileBase = path.parse(file).name;
                
                const galleryFilename = `${fileBase}-gallery-1280.webp`;
                const galleryOutputPath = path.join(optimizedFolderPath, galleryFilename);
                const galleryUrl = encodeURI(`/optimized/${folder}/${galleryFilename}`);
                
                // Keep track of gallery paths
                galleryImages.push(galleryUrl);

                // Generate Gallery version (1280px wide max, 80% quality)
                if (!fs.existsSync(galleryOutputPath)) {
                    await sharp(inputPath)
                        .resize({ width: 1280, withoutEnlargement: true })
                        .webp({ quality: 80, effort: 4 })
                        .toFile(galleryOutputPath)
                        .catch(err => console.error(`Error processing ${inputPath}:`, err));
                }

                // If it's the first image, also make a cover version (480px)
                if (i === 0) {
                    const coverFilename = `${fileBase}-cover-480.webp`;
                    const coverOutputPath = path.join(optimizedFolderPath, coverFilename);
                    coverImage = encodeURI(`/optimized/${folder}/${coverFilename}`);
                    
                    if (!fs.existsSync(coverOutputPath)) {
                        await sharp(inputPath)
                            .resize({ width: 480, withoutEnlargement: true })
                            .webp({ quality: 80, effort: 4 })
                            .toFile(coverOutputPath)
                            .catch(err => console.error(`Error processing cover ${inputPath}:`, err));
                    }
                }
            }

            projects.push({
                title: title,
                slug: slug,
                role: "Dẫn chương trình",
                image: coverImage
            });
            
            projectDetails[slug] = {
                title: title,
                images: galleryImages
            };
        }
    }

    const content = `// Auto-generated by prebuild.js
export const projects = ${JSON.stringify(projects, null, 2)};

export const projectDetails: Record<string, { title: string, images: string[] }> = ${JSON.stringify(projectDetails, null, 2)};
`;

    fs.writeFileSync(dataFile, content, 'utf8');
    console.log('Image optimization complete. Generated data.ts pointing to lightweight webp!');
}

run();
