/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#00111f",
        "secondary": "#5f5e5e",
        "surface-bright": "#fffae7",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#003550",
        "inverse-surface": "#fffae7",
        "surface-tint": "#0a4275",
        "error": "#ba1a1a",
        "inverse-primary": "#91c8f9",
        "on-tertiary-container": "#001f33",
        "outline-variant": "#d1c5b4",
        "secondary-fixed-dim": "#c8c6c5",
        "on-background": "#1c1c18",
        "on-surface": "#1c1c18",
        "secondary-container": "#fffae7",
        "primary-fixed-dim": "#91c8f9",
        "on-error": "#ffffff",
        "tertiary": "#005c8a",
        "background": "#fffae7",
        "primary": "#0a4275",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#fffae7",
        "tertiary-container": "#60b9d8",
        "on-surface-variant": "#4e4639",
        "tertiary-fixed-dim": "#80d4f6",
        "tertiary-fixed": "#c2e7ff",
        "primary-container": "#6ba3d6",
        "outline": "#7f7667",
        "surface-container-lowest": "#fffae7",
        "surface-variant": "#fffae7",
        "surface-container-high": "#fffae7",
        "on-primary-container": "#001d36",
        "on-secondary-container": "#656464",
        "surface-container-low": "#fffae7",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d1e4ff",
        "surface": "#fffae7",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#1c1c18",
        "on-primary-fixed": "#000f1c",
        "secondary-fixed": "#fffae7",
        "on-secondary-fixed-variant": "#474747",
        "surface-dim": "#fffae7",
        "surface-container": "#fffae7",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#003355"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Inter"],
        "label": ["Inter"],
        "serif": ["Noto Serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}

