// Auto-generated by generate_static_data.js
export const projects = [
  {
    "title": "Biểu diễn nghệ thuật 20-11",
    "slug": "bieu-dien-nghe-thuat-20-11",
    "role": "Dẫn chương trình",
    "image": "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_2133.JPG"
  },
  {
    "title": "Host",
    "slug": "host",
    "role": "Dẫn chương trình",
    "image": "/Host/att.BQB2uBNynzS33q3c2l1B1r0nuS-xMwKoPF_QYEoHHLw.JPG"
  },
  {
    "title": "Hội Làng 2025",
    "slug": "hoi-lang-2025",
    "role": "Dẫn chương trình",
    "image": "/H%E1%BB%99i%20L%C3%A0ng%202025/ChuHai--13.jpeg"
  },
  {
    "title": "Hội thảo cô Lệ Chi",
    "slug": "hoi-thao-co-le-chi",
    "role": "Dẫn chương trình",
    "image": "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/3786cf70cbfa09419525419a8e037b1b.JPG"
  },
  {
    "title": "Hội thảo khởi nghiệp",
    "slug": "hoi-thao-khoi-nghiep",
    "role": "Dẫn chương trình",
    "image": "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250528234838286.jpg"
  },
  {
    "title": "Kỉ niệm 50 năm",
    "slug": "ki-niem-50-nam",
    "role": "Dẫn chương trình",
    "image": "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/DZIIST-19.jpeg"
  },
  {
    "title": "MC Thảm đỏ Lễ Tôn Vinh",
    "slug": "mc-tham-do-le-ton-vinh",
    "role": "Dẫn chương trình",
    "image": "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2179.JPG"
  },
  {
    "title": "Open Mic ",
    "slug": "open-mic_",
    "role": "Dẫn chương trình",
    "image": "/Open%20Mic_/ChuHai--2_Original.JPG"
  },
  {
    "title": "RESCONNECT 2025",
    "slug": "resconnect-2025",
    "role": "Dẫn chương trình",
    "image": "/RESCONNECT%202025/ChuHai-00464_Original.JPG"
  },
  {
    "title": "Talkshow MC Thời sự",
    "slug": "talkshow-mc-thoi-su",
    "role": "Dẫn chương trình",
    "image": "/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2756.JPG"
  },
  {
    "title": "Triển lãm tại Bảo tàng ĐN",
    "slug": "trien-lam-tai-bao-tang-dn",
    "role": "Dẫn chương trình",
    "image": "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-11.jpeg"
  },
  {
    "title": "Triển Lãm tại công viên APEC",
    "slug": "trien-lam-tai-cong-vien-apec",
    "role": "Dẫn chương trình",
    "image": "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1864.JPG"
  }
];

export const projectDetails: Record<string, { title: string, images: string[] }> = {
  "bieu-dien-nghe-thuat-20-11": {
    "title": "Biểu diễn nghệ thuật 20-11",
    "images": [
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_2133.JPG",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_2134.JPG",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_8414.JPG",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_8428.JPG",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_8429.JPG",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/quality_restoration_20241203002733622.jpg",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/quality_restoration_20241203003517420.jpg",
      "/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/quality_restoration_20241203003552276.jpg"
    ]
  },
  "host": {
    "title": "Host",
    "images": [
      "/Host/att.BQB2uBNynzS33q3c2l1B1r0nuS-xMwKoPF_QYEoHHLw.JPG",
      "/Host/att.H7tS-Ll6wHC-dmiRKOn5KVHgheTxxAqLhDEsTcddTE0.jpg",
      "/Host/att.RoXaBf5dbCu7ITZpIsYoMgAazZK9G-5PCkU98q0Op4M.jpg",
      "/Host/att.VE5CYV93dp93vmEEascFbSBZkS5B9OBit2njIP-8_0I.jpg",
      "/Host/att.WFJQMLYdujg8obsVIbVq5kFMV4B0pudjZIBWKu-yMK8.JPG",
      "/Host/ChuHai-05134_Original.JPG",
      "/Host/ChuHai-05139_Original.JPG",
      "/Host/ChuHai-05156_Original.JPG",
      "/Host/ChuHai-05166_Original.JPG",
      "/Host/FPT%20Podcast%20S25%2021-32.JPEG",
      "/Host/IMG_2097.JPG",
      "/Host/IMG_2098.JPG",
      "/Host/IMG_2106.JPG"
    ]
  },
  "hoi-lang-2025": {
    "title": "Hội Làng 2025",
    "images": [
      "/H%E1%BB%99i%20L%C3%A0ng%202025/ChuHai--13.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/ChuHai-06750.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09092.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09094.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09098.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09103.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09106.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_7254.JPG",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_7255.JPG",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_7261.JPG",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_8640.JPG",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_8740.JPG",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/ROO01652.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/ROO01806.jpeg",
      "/H%E1%BB%99i%20L%C3%A0ng%202025/ROO01839.jpeg"
    ]
  },
  "hoi-thao-co-le-chi": {
    "title": "Hội thảo cô Lệ Chi",
    "images": [
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/3786cf70cbfa09419525419a8e037b1b.JPG",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_1918.JPG",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_1947.JPG",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_2854.JPG",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_2855.JPG",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_2856.JPG",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/quality_restoration_20250603103646263.JPG"
    ]
  },
  "hoi-thao-khoi-nghiep": {
    "title": "Hội thảo khởi nghiệp",
    "images": [
      "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250528234838286.jpg",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250528234852927.jpg",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250921190942776.jpeg",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/THT_4973.jpeg",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/THT_4977.jpeg",
      "/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/THT_5128.jpeg"
    ]
  },
  "ki-niem-50-nam": {
    "title": "Kỉ niệm 50 năm",
    "images": [
      "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/DZIIST-19.jpeg",
      "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_1354.JPG",
      "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_1355.JPG",
      "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_7852.JPG",
      "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_9911.JPG",
      "/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_9912.JPG"
    ]
  },
  "mc-tham-do-le-ton-vinh": {
    "title": "MC Thảm đỏ Lễ Tôn Vinh",
    "images": [
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2179.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2181.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2998.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2999.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3001.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3002.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3036.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3037.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3039.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3041.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3056.JPG",
      "/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3057.JPG"
    ]
  },
  "open-mic_": {
    "title": "Open Mic ",
    "images": [
      "/Open%20Mic_/ChuHai--2_Original.JPG",
      "/Open%20Mic_/ChuHai-00055_Original.JPG",
      "/Open%20Mic_/ChuHai-00167_Original.JPG",
      "/Open%20Mic_/ChuHai-00168_Original.JPG",
      "/Open%20Mic_/ChuHai-00173_Original.JPG",
      "/Open%20Mic_/ChuHai-00207_Original.JPG",
      "/Open%20Mic_/ChuHai-08326_Original.JPG",
      "/Open%20Mic_/ChuHai-08530-2_Original.JPG",
      "/Open%20Mic_/ChuHai-08659_Original.JPG",
      "/Open%20Mic_/ChuHai-09061_Original.JPG",
      "/Open%20Mic_/ChuHai-09271_Original.JPG",
      "/Open%20Mic_/ChuHai-09276_Original.JPG",
      "/Open%20Mic_/ChuHai-_Original.JPG",
      "/Open%20Mic_/Openmic%2021.JPEG",
      "/Open%20Mic_/Openmic%203.JPEG",
      "/Open%20Mic_/Openmic%2084.JPEG",
      "/Open%20Mic_/quality_restoration_20251125174306862.jpeg"
    ]
  },
  "resconnect-2025": {
    "title": "RESCONNECT 2025",
    "images": [
      "/RESCONNECT%202025/ChuHai-00464_Original.JPG",
      "/RESCONNECT%202025/ChuHai-00562_Original.jpg",
      "/RESCONNECT%202025/ChuHai-00565_Original.jpg",
      "/RESCONNECT%202025/ChuHai-00578_Original.jpg",
      "/RESCONNECT%202025/ChuHai-00579_Original.jpg",
      "/RESCONNECT%202025/ChuHai-00769_Original.JPG",
      "/RESCONNECT%202025/IMG_2176.JPG",
      "/RESCONNECT%202025/IMG_2177.JPG",
      "/RESCONNECT%202025/IMG_2178.JPG",
      "/RESCONNECT%202025/IMG_9696.JPG",
      "/RESCONNECT%202025/IMG_9697.JPG"
    ]
  },
  "talkshow-mc-thoi-su": {
    "title": "Talkshow MC Thời sự",
    "images": [
      "/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2756.JPG",
      "/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2782.JPG",
      "/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2783.JPG",
      "/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2784.JPG"
    ]
  },
  "trien-lam-tai-bao-tang-dn": {
    "title": "Triển lãm tại Bảo tàng ĐN",
    "images": [
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-11.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-13.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-16.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-32.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-33.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-4.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_1927.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_1928.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_1929.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2155.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2156.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2157.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2161.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2162.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2163.JPG",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_7691-Enhanced-NR.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_7693-Enhanced-NR.jpeg",
      "/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_7801-Enhanced-NR.jpeg"
    ]
  },
  "trien-lam-tai-cong-vien-apec": {
    "title": "Triển Lãm tại công viên APEC",
    "images": [
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1864.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1865.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1868.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1880.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2152.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2153.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2154.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2158.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2159.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2160.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_6536.jpeg",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_6669.jpeg",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_6704.jpeg",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_8862.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_8867.JPG",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/quality_restoration_20251122155125274.jpeg",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/quality_restoration_20251123081727906.jpeg",
      "/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/quality_restoration_20251123081842590.jpeg"
    ]
  }
};
