// Auto-generated by prebuild.js
export const projects = [
  {
    "title": "Biểu diễn nghệ thuật 20-11",
    "slug": "bieu-dien-nghe-thuat-20-11",
    "role": "Dẫn chương trình",
    "image": "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_2133-cover-480.webp"
  },
  {
    "title": "Host",
    "slug": "host",
    "role": "Dẫn chương trình",
    "image": "/optimized/Host/att.BQB2uBNynzS33q3c2l1B1r0nuS-xMwKoPF_QYEoHHLw-cover-480.webp"
  },
  {
    "title": "Hội Làng 2025",
    "slug": "hoi-lang-2025",
    "role": "Dẫn chương trình",
    "image": "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/ChuHai--13-cover-480.webp"
  },
  {
    "title": "Hội thảo cô Lệ Chi",
    "slug": "hoi-thao-co-le-chi",
    "role": "Dẫn chương trình",
    "image": "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/3786cf70cbfa09419525419a8e037b1b-cover-480.webp"
  },
  {
    "title": "Hội thảo khởi nghiệp",
    "slug": "hoi-thao-khoi-nghiep",
    "role": "Dẫn chương trình",
    "image": "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250528234838286-cover-480.webp"
  },
  {
    "title": "Kỉ niệm 50 năm",
    "slug": "ki-niem-50-nam",
    "role": "Dẫn chương trình",
    "image": "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/DZIIST-19-cover-480.webp"
  },
  {
    "title": "MC Thảm đỏ Lễ Tôn Vinh",
    "slug": "mc-tham-do-le-ton-vinh",
    "role": "Dẫn chương trình",
    "image": "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2179-cover-480.webp"
  },
  {
    "title": "Open Mic ",
    "slug": "open-mic_",
    "role": "Dẫn chương trình",
    "image": "/optimized/Open%20Mic_/ChuHai--2_Original-cover-480.webp"
  },
  {
    "title": "RESCONNECT 2025",
    "slug": "resconnect-2025",
    "role": "Dẫn chương trình",
    "image": "/optimized/RESCONNECT%202025/ChuHai-00464_Original-cover-480.webp"
  },
  {
    "title": "Talkshow MC Thời sự",
    "slug": "talkshow-mc-thoi-su",
    "role": "Dẫn chương trình",
    "image": "/optimized/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2756-cover-480.webp"
  },
  {
    "title": "Triển lãm tại Bảo tàng ĐN",
    "slug": "trien-lam-tai-bao-tang-dn",
    "role": "Dẫn chương trình",
    "image": "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-11-cover-480.webp"
  },
  {
    "title": "Triển Lãm tại công viên APEC",
    "slug": "trien-lam-tai-cong-vien-apec",
    "role": "Dẫn chương trình",
    "image": "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1864-cover-480.webp"
  }
];

export const projectDetails: Record<string, { title: string, images: string[] }> = {
  "bieu-dien-nghe-thuat-20-11": {
    "title": "Biểu diễn nghệ thuật 20-11",
    "images": [
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_2133-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_2134-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_8414-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_8428-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/IMG_8429-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/quality_restoration_20241203002733622-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/quality_restoration_20241203003517420-gallery-1280.webp",
      "/optimized/Bi%E1%BB%83u%20di%E1%BB%85n%20ngh%E1%BB%87%20thu%E1%BA%ADt%2020-11/quality_restoration_20241203003552276-gallery-1280.webp"
    ]
  },
  "host": {
    "title": "Host",
    "images": [
      "/optimized/Host/att.BQB2uBNynzS33q3c2l1B1r0nuS-xMwKoPF_QYEoHHLw-gallery-1280.webp",
      "/optimized/Host/att.H7tS-Ll6wHC-dmiRKOn5KVHgheTxxAqLhDEsTcddTE0-gallery-1280.webp",
      "/optimized/Host/att.RoXaBf5dbCu7ITZpIsYoMgAazZK9G-5PCkU98q0Op4M-gallery-1280.webp",
      "/optimized/Host/att.VE5CYV93dp93vmEEascFbSBZkS5B9OBit2njIP-8_0I-gallery-1280.webp",
      "/optimized/Host/att.WFJQMLYdujg8obsVIbVq5kFMV4B0pudjZIBWKu-yMK8-gallery-1280.webp",
      "/optimized/Host/ChuHai-05134_Original-gallery-1280.webp",
      "/optimized/Host/ChuHai-05139_Original-gallery-1280.webp",
      "/optimized/Host/ChuHai-05156_Original-gallery-1280.webp",
      "/optimized/Host/ChuHai-05166_Original-gallery-1280.webp",
      "/optimized/Host/FPT%20Podcast%20S25%2021-32-gallery-1280.webp",
      "/optimized/Host/IMG_2097-gallery-1280.webp",
      "/optimized/Host/IMG_2098-gallery-1280.webp",
      "/optimized/Host/IMG_2106-gallery-1280.webp"
    ]
  },
  "hoi-lang-2025": {
    "title": "Hội Làng 2025",
    "images": [
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/ChuHai--13-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/ChuHai-06750-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09092-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09094-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09098-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09103-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/HY_09106-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_7254-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_7255-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_7261-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_8640-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/IMG_8740-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/ROO01652-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/ROO01806-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20L%C3%A0ng%202025/ROO01839-gallery-1280.webp"
    ]
  },
  "hoi-thao-co-le-chi": {
    "title": "Hội thảo cô Lệ Chi",
    "images": [
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/3786cf70cbfa09419525419a8e037b1b-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_1918-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_1947-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_2854-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_2855-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/IMG_2856-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20c%C3%B4%20L%E1%BB%87%20Chi/quality_restoration_20250603103646263-gallery-1280.webp"
    ]
  },
  "hoi-thao-khoi-nghiep": {
    "title": "Hội thảo khởi nghiệp",
    "images": [
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250528234838286-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250528234852927-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/quality_restoration_20250921190942776-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/THT_4973-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/THT_4977-gallery-1280.webp",
      "/optimized/H%E1%BB%99i%20th%E1%BA%A3o%20kh%E1%BB%9Fi%20nghi%E1%BB%87p/THT_5128-gallery-1280.webp"
    ]
  },
  "ki-niem-50-nam": {
    "title": "Kỉ niệm 50 năm",
    "images": [
      "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/DZIIST-19-gallery-1280.webp",
      "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_1354-gallery-1280.webp",
      "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_1355-gallery-1280.webp",
      "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_7852-gallery-1280.webp",
      "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_9911-gallery-1280.webp",
      "/optimized/K%E1%BB%89%20ni%E1%BB%87m%2050%20n%C4%83m/IMG_9912-gallery-1280.webp"
    ]
  },
  "mc-tham-do-le-ton-vinh": {
    "title": "MC Thảm đỏ Lễ Tôn Vinh",
    "images": [
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2179-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2181-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2998-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_2999-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3001-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3002-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3036-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3037-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3039-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3041-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3056-gallery-1280.webp",
      "/optimized/MC%20Th%E1%BA%A3m%20%C4%91%E1%BB%8F%20L%E1%BB%85%20T%C3%B4n%20Vinh/IMG_3057-gallery-1280.webp"
    ]
  },
  "open-mic_": {
    "title": "Open Mic ",
    "images": [
      "/optimized/Open%20Mic_/ChuHai--2_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-00055_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-00167_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-00168_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-00173_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-00207_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-08326_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-08530-2_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-08659_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-09061_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-09271_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-09276_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/ChuHai-_Original-gallery-1280.webp",
      "/optimized/Open%20Mic_/Openmic%2021-gallery-1280.webp",
      "/optimized/Open%20Mic_/Openmic%203-gallery-1280.webp",
      "/optimized/Open%20Mic_/Openmic%2084-gallery-1280.webp",
      "/optimized/Open%20Mic_/quality_restoration_20251125174306862-gallery-1280.webp"
    ]
  },
  "resconnect-2025": {
    "title": "RESCONNECT 2025",
    "images": [
      "/optimized/RESCONNECT%202025/ChuHai-00464_Original-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/ChuHai-00562_Original-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/ChuHai-00565_Original-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/ChuHai-00578_Original-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/ChuHai-00579_Original-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/ChuHai-00769_Original-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/IMG_2176-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/IMG_2177-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/IMG_2178-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/IMG_9696-gallery-1280.webp",
      "/optimized/RESCONNECT%202025/IMG_9697-gallery-1280.webp"
    ]
  },
  "talkshow-mc-thoi-su": {
    "title": "Talkshow MC Thời sự",
    "images": [
      "/optimized/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2756-gallery-1280.webp",
      "/optimized/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2782-gallery-1280.webp",
      "/optimized/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2783-gallery-1280.webp",
      "/optimized/Talkshow%20MC%20Th%E1%BB%9Di%20s%E1%BB%B1/IMG_2784-gallery-1280.webp"
    ]
  },
  "trien-lam-tai-bao-tang-dn": {
    "title": "Triển lãm tại Bảo tàng ĐN",
    "images": [
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-11-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-13-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-16-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-32-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-33-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/img-4-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_1927-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_1928-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_1929-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2155-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2156-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2157-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2161-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2162-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_2163-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_7691-Enhanced-NR-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_7693-Enhanced-NR-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20l%C3%A3m%20t%E1%BA%A1i%20B%E1%BA%A3o%20t%C3%A0ng%20%C4%90N/IMG_7801-Enhanced-NR-gallery-1280.webp"
    ]
  },
  "trien-lam-tai-cong-vien-apec": {
    "title": "Triển Lãm tại công viên APEC",
    "images": [
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1864-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1865-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1868-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_1880-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2152-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2153-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2154-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2158-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2159-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_2160-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_6536-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_6669-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_6704-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_8862-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/IMG_8867-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/quality_restoration_20251122155125274-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/quality_restoration_20251123081727906-gallery-1280.webp",
      "/optimized/Tri%E1%BB%83n%20L%C3%A3m%20t%E1%BA%A1i%20c%C3%B4ng%20vi%C3%AAn%20APEC/quality_restoration_20251123081842590-gallery-1280.webp"
    ]
  }
};
